version: "3.8"

networks:
  dht:
    name: "dht"
    driver: bridge
    attachable: true

services:
  registry:
    build:
      context: ../
      dockerfile: clusters/Dockerfile.registry
    environment:
      - REGISTRY_HOSTNAME=registry
    networks:
      - dht
  
  dht-node-1:
    build:
      context: ../
      dockerfile: clusters/Dockerfile.dht
    depends_on:
      - registry
    environment:
      - REGISTRY_HOSTNAME=registry
      - NODE_HOSTNAME=dht-node-1
    networks:
      - dht
    command: "50001"

  dht-node-2:
    build:
      context: ../
      dockerfile: clusters/Dockerfile.dht
    depends_on:
      - registry
      - dht-node-1
    environment:
      - REGISTRY_HOSTNAME=registry
      - NODE_HOSTNAME=dht-node-2
    networks:
      - dht
    command: "50002"

  dht-node-3:
    build:
      context: ../
      dockerfile: clusters/Dockerfile.dht
    depends_on:
      - registry
      - dht-node-2
    environment:
      - REGISTRY_HOSTNAME=registry
      - NODE_HOSTNAME=dht-node-3
    networks:
      - dht
    command: "50003"

  dht-node-4:
    build:
      context: ../
      dockerfile: clusters/Dockerfile.dht
    depends_on:
      - registry
      - dht-node-3
    environment:
      - REGISTRY_HOSTNAME=registry
      - NODE_HOSTNAME=dht-node-4
    networks:
      - dht
    command: "50004"

  dht-node-5:
    build:
      context: ../
      dockerfile: clusters/Dockerfile.dht
    depends_on:
      - registry
      - dht-node-4
    environment:
      - REGISTRY_HOSTNAME=registry
      - NODE_HOSTNAME=dht-node-5
    networks:
      - dht
    command: "50005"